lstWeekDays = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
print(lstWeekDays[0])
print(lstWeekDays[1])
print(lstWeekDays[2])
print(lstWeekDays[3])
print(lstWeekDays[4])
print(lstWeekDays[5])
print(lstWeekDays[6])
print("Print Reverse Order:")
print(lstWeekDays[-1])
print(lstWeekDays[-2])
print(lstWeekDays[-3])
print(lstWeekDays[-4])
print(lstWeekDays[-5])
print(lstWeekDays[-6])
print(lstWeekDays[-7])
